services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: cem
      POSTGRES_PASSWORD: cem
      POSTGRES_DB: cem
    ports:
      - '5432:5432'
    volumes:
      - cem_pgdata:/var/lib/postgresql/data

volumes:
  cem_pgdata: